# Generated by Django 4.2.2 on 2023-06-19 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editeur',
            fields=[
                ('id_editeur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_editeur', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'editeur',
            },
        ),
        migrations.CreateModel(
            name='Jeu',
            fields=[
                ('id_jeu', models.AutoField(primary_key=True, serialize=False)),
                ('nom_jeu', models.CharField(max_length=50)),
                ('date_publication', models.DateField()),
                ('age_min', models.IntegerField()),
                ('joueurs_min', models.IntegerField()),
                ('joueurs_max', models.IntegerField()),
                ('id_editeur', models.ForeignKey(db_column='id_editeur', on_delete=django.db.models.deletion.DO_NOTHING, to='api.editeur')),
            ],
            options={
                'db_table': 'jeu',
            },
        ),
    ]
