# Generated by Django 4.2.2 on 2023-06-20 05:00

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeu',
            name='age_min',
            field=models.IntegerField(validators=[api.models.valider_positif]),
        ),
    ]
