# Generated by Django 4.2.2 on 2023-06-20 05:17

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_jeu_age_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeu',
            name='joueurs_max',
            field=models.IntegerField(validators=[api.models.valider_positif]),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='joueurs_min',
            field=models.IntegerField(validators=[api.models.valider_positif]),
        ),
    ]
