# Generated by Django 4.2.2 on 2023-06-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_jeu_joueurs_max_alter_jeu_joueurs_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeu',
            name='joueurs_min',
            field=models.IntegerField(),
        ),
    ]
